//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallReminder.Core.Resourses {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CallReminder.Core.Resourses.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call Reminder.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call.
        /// </summary>
        public static string CallActionNotification {
            get {
                return ResourceManager.GetString("CallActionNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelActionNotification {
            get {
                return ResourceManager.GetString("CancelActionNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill required fields.
        /// </summary>
        public static string FillRequiredField {
            get {
                return ResourceManager.GetString("FillRequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of contact.
        /// </summary>
        public static string HintNameContactTextView {
            get {
                return ResourceManager.GetString("HintNameContactTextView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone of contact.
        /// </summary>
        public static string HintPhoneContactTextView {
            get {
                return ResourceManager.GetString("HintPhoneContactTextView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reminder call to.
        /// </summary>
        public static string ReminderCallTo {
            get {
                return ResourceManager.GetString("ReminderCallTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reminder set: {0}.
        /// </summary>
        public static string ReminderSetFormatWithOneParam {
            get {
                return ResourceManager.GetString("ReminderSetFormatWithOneParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field can&apos;t empty.
        /// </summary>
        public static string RequiredFieldError {
            get {
                return ResourceManager.GetString("RequiredFieldError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select fields.
        /// </summary>
        public static string SelectFields {
            get {
                return ResourceManager.GetString("SelectFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call.
        /// </summary>
        public static string TitleCallButton {
            get {
                return ResourceManager.GetString("TitleCallButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choice contact.
        /// </summary>
        public static string TitleContactPage {
            get {
                return ResourceManager.GetString("TitleContactPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit contact.
        /// </summary>
        public static string TitleDetailPage {
            get {
                return ResourceManager.GetString("TitleDetailPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reminder.
        /// </summary>
        public static string TitleHomePage {
            get {
                return ResourceManager.GetString("TitleHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reminder.
        /// </summary>
        public static string TitleNotificationPage {
            get {
                return ResourceManager.GetString("TitleNotificationPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string TitleRemoveButton {
            get {
                return ResourceManager.GetString("TitleRemoveButton", resourceCulture);
            }
        }
    }
}
